
version: 2
jobs:
  build:
    working_directory: ~/CalcMoy
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "domain/build.gradle" }}-{{ checksum  "data/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key:  jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "domain/build.gradle" }}
                         -{{ checksum  "data/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
          destination: test-results/
      - run:
          name: Initial build
          command: ./gradlew clean assembleDebug --no-daemon
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/